-- ============================================================================
-- MNR Cycle Mart — Initial schema, seed data, and RLS policies
-- Run this in the Supabase SQL Editor (or `supabase db push`) for the project
-- ref idjoxfazivjufbmunnetk.
--
-- NOTE: Uses `CREATE TABLE IF NOT EXISTS` and `ON CONFLICT DO NOTHING` so it is
-- safe to run even if equivalent tables / rows already exist (no duplicates).
-- ============================================================================

-- ────────────────────────────────────────────────────────────────────────────
-- PRODUCTS
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.products (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL,
  category    text NOT NULL,
  price       numeric NOT NULL DEFAULT 0,
  stock       integer NOT NULL DEFAULT 0,
  status      text NOT NULL DEFAULT 'Active',
  sku         text,
  hsn_code    text,
  unit        text DEFAULT 'Nos',
  image       text DEFAULT '🚲',
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- ────────────────────────────────────────────────────────────────────────────
-- CUSTOMERS
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.customers (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL,
  email       text,
  phone       text,
  orders      integer NOT NULL DEFAULT 0,
  total_spent numeric NOT NULL DEFAULT 0,
  join_date   text,
  address     text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- ────────────────────────────────────────────────────────────────────────────
-- ORDERS
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.orders (
  id          text PRIMARY KEY,          -- e.g. #ORD1284
  customer    text,
  email       text,
  phone       text,
  items       integer NOT NULL DEFAULT 0,
  amount      numeric NOT NULL DEFAULT 0,
  status      text,
  date        text,                      -- display date, e.g. 'Sep 15, 2025'
  address     text,
  invoice_no  text,                      -- link to bills.invoice_no
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- ────────────────────────────────────────────────────────────────────────────
-- BILLS (invoice header + line items as JSON)
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.bills (
  invoice_no      text PRIMARY KEY,      -- e.g. MNR-INV-20260917-0001
  date            text,                  -- 'YYYY-MM-DD'
  customer_name   text NOT NULL,
  customer_phone  text,
  customer_address text,
  customer_email  text,
  items           jsonb NOT NULL DEFAULT '[]'::jsonb,
  subtotal        numeric NOT NULL DEFAULT 0,
  discount        numeric NOT NULL DEFAULT 0,
  discount_type   text DEFAULT '%',
  discount_amt    numeric NOT NULL DEFAULT 0,
  igst_total      numeric NOT NULL DEFAULT 0,
  grand_total     numeric NOT NULL DEFAULT 0,
  payment_method  text,
  payment_status  text DEFAULT 'Paid',
  status          text NOT NULL DEFAULT 'Active',
  created_at      timestamptz,
  updated_at      timestamptz NOT NULL DEFAULT now()
);

-- ============================================================================
-- SEED DATA  (idempotent — matches the app's existing seed arrays)
-- ============================================================================

INSERT INTO public.products (id, name, category, price, stock, status, sku, hsn_code, unit, image) VALUES
  (1, 'Mountain Explorer Pro', 'Mountain Bike', 24999, 12, 'Active',       'MNR-MOU-001', '8712', 'Nos', '🚲'),
  (2, 'City Rider 21 Speed',   'Road Bike',      18499,  8, 'Active',       'MNR-ROA-002', '8712', 'Nos', '🚲'),
  (3, 'Kids Fun Cycle',        'Kids Bike',      6999,  25, 'Active',       'MNR-KID-003', '8712', 'Nos', '🚲'),
  (4, 'Electric EcoRide',       'E-Bike',        45999,  5, 'Low Stock',    'MNR-EBI-004', '8714', 'Nos', '🔋'),
  (5, 'Hybrid Comfort Plus',    'Hybrid',        15999,  0, 'Out of Stock', 'MNR-HYB-005', '8712', 'Nos', '🚲'),
  (6, 'Safety Helmet Pro',      'Accessories',    1299, 45, 'Active',       'MNR-ACC-006', '6506', 'Nos', '⛑️'),
  (7, 'Cycle Bell Deluxe',      'Accessories',     299, 80, 'Active',       'MNR-ACC-007', '8714', 'Nos', '🔔'),
  (8, 'Water Bottle Cage',      'Accessories',     499, 60, 'Active',       'MNR-ACC-008', '8714', 'Nos', '🧴')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.customers (id, name, email, phone, orders, total_spent, join_date, address) VALUES
  (1, 'Ravi Kumar',   'ravi@email.com',    '9876543210', 5, 45999, 'Jan 2025', 'Hyderabad, Telangana'),
  (2, 'Priya Sharma', 'priya@email.com',   '8765432109', 3, 37497, 'Mar 2025', 'Bangalore, Karnataka'),
  (3, 'Karthik S',    'karthik@email.com', '7654321098', 8, 89992, 'Feb 2025', 'Chennai, Tamil Nadu'),
  (4, 'Anjali Reddy', 'anjali@email.com',  '6543210987', 2, 31998, 'Jun 2025', 'Pune, Maharashtra'),
  (5, 'Suresh Babu',  'suresh@email.com',  '5432109876', 6, 56994, 'Apr 2025', 'Mumbai, Maharashtra')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.orders (id, customer, email, phone, items, amount, status, date, address, invoice_no) VALUES
  ('#ORD1284', 'Ravi Kumar',   'ravi@email.com',    '+91 98765 43210', 2,  8999, 'Delivered',  'Sep 15, 2025', '123 Main St, Hyderabad', NULL),
  ('#ORD1283', 'Priya Sharma', 'priya@email.com',   '+91 87654 32109', 1, 12499, 'Shipped',    'Sep 14, 2025', '456 Park Ave, Bangalore', NULL),
  ('#ORD1282', 'Karthik S',    'karthik@email.com', '+91 76543 21098', 3,  6799, 'Processing', 'Sep 14, 2025', '789 Lake Rd, Chennai', NULL),
  ('#ORD1281', 'Anjali Reddy', 'anjali@email.com',  '+91 65432 10987', 1, 15999, 'Delivered',  'Sep 13, 2025', '321 Hill St, Pune', NULL),
  ('#ORD1280', 'Suresh Babu',  'suresh@email.com',  '+91 54321 09876', 2,  9499, 'Shipped',    'Sep 13, 2025', '654 Valley Rd, Mumbai', NULL),
  ('#ORD1279', 'Meena Devi',   'meena@email.com',   '+91 43210 98765', 1, 24999, 'Cancelled',  'Sep 12, 2025', '987 Garden St, Delhi', NULL)
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- ROW LEVEL SECURITY
--
-- The browser app authenticates with the PUBLISHABLE (anon) key and its own
-- in-app admin session (AuthContext), so these tables must be readable /
-- writable by the anon role for the app to function. Policies below grant
-- full CRUD to anon + authenticated for the app's data tables.
--
-- ⚠️  For production hardening: tie policies to a real Supabase Auth user
--     (e.g. `TO authenticated USING (auth.uid() IS NOT NULL)`) and route
--     privileged writes through an Edge Function using the SECRET key.
--     The service-role key must NEVER be used in browser code.
-- ============================================================================

ALTER TABLE public.products  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bills     ENABLE ROW LEVEL SECURITY;

CREATE POLICY "products_all"  ON public.products  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "customers_all" ON public.customers FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "orders_all"    ON public.orders    FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "bills_all"     ON public.bills     FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);