-- ============================================================================
-- MNR Cycle Mart — Notifications
-- Supports the notification bell in the navbar. Real notifications are
-- inserted by the app (e.g. when a new order/bill is created) and streamed
-- to the UI in real time via Supabase Realtime.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.notifications (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       text NOT NULL,
  message     text NOT NULL,
  is_read     boolean NOT NULL DEFAULT false,
  created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "notifications_all" ON public.notifications
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- Realtime: allow the app to subscribe to inserts/updates/deletes.
-- (Supabase only requires tables to be added to the publication once; this
--  statement is idempotent so it can be re-run safely.)
ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;